### ISSUE TITLE
kibana can't authenticate after installing "datasweet formula" plugin

### ISSUE THREAD

**Issue by mahmoudtweb** [datasweet-fr/kibana-datasweet-formula#1]
Hi, after installing kibana-datasweet-formula kibana can't authenticate 
the error bellow is displayed when clicking on logout or timelion OR logging in

* Search Guard and Elasticsearch version
      search guard search-guard-6:6.1.0-20.1
      search-guard-kibana-plugin-6.1.0-8
      elastic stack 6.1.0 (docker containers)

* Search Guard configuration files
    copy of https://github.com/deviantony/docker-elk/tree/searchguard

* Other installed Elasticsearch or Kibana plugins, if any
   kibana-datasweet-formula 

* Error
`Error: Uncaught Error: [$injector:modulerr] Failed to instantiate module kibana due to:
Error: [$injector:modulerr] Failed to instantiate module app/visualize due to:
Error: [$injector:unpr] Unknown provider: visEditorAggDirectiveProvider
http://errors.angularjs.org/1.6.5/$injector/unpr?p0=visEditorAggDirectiveProvider
    at http://localhost:5696/bundles/commons.bundle.js?v=16337:48:996
    at http://localhost:5696/bundles/commons.bundle.js?v=16337:48:34101
    at Object.getService [as get] (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:32180)
    at Object.decorator (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:30436)
    at http://localhost:5696/bundles/commons.bundle.js?v=16337:7:74957
    at Object.invoke (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:33212)
    at runInvokeQueue (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:31027)
    at http://localhost:5696/bundles/commons.bundle.js?v=16337:48:31338
    at forEach (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:1681)
    at loadModules (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:30821)
http://errors.angularjs.org/1.6.5/$injector/modulerr?p0=app%2Fvisualize&p1=Error%3A%20%5B%24injector%3Aunpr%5D%20Unknown%20provider%3A%20visEditorAggDirectiveProvider%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.5%2F%24injector%2Funpr%3Fp0%3DvisEditorAggDirectiveProvider%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A996%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A34101%0A%20%20%20%20at%20Object.getService%20%5Bas%20get%5D%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A32180)%0A%20%20%20%20at%20Object.decorator%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A30436)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A7%3A74957%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A33212)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A31027)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A31338%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A30821)
    at http://localhost:5696/bundles/commons.bundle.js?v=16337:48:996
    at http://localhost:5696/bundles/commons.bundle.js?v=16337:48:31683
    at forEach (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:1681)
    at loadModules (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:30821)
    at http://localhost:5696/bundles/commons.bundle.js?v=16337:48:31240
    at forEach (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:1681)
    at loadModules (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:30821)
    at createInjector (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:34614)
    at doBootstrap (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:13733)
    at Object.bootstrap (http://localhost:5696/bundles/commons.bundle.js?v=16337:48:14265)
http://errors.angularjs.org/1.6.5/$injector/modulerr?p0=kibana&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20app%2Fvisualize%20due%20to%3A%0AError%3A%20%5B%24injector%3Aunpr%5D%20Unknown%20provider%3A%20visEditorAggDirectiveProvider%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.5%2F%24injector%2Funpr%3Fp0%3DvisEditorAggDirectiveProvider%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A996%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A34101%0A%20%20%20%20at%20Object.getService%20%5Bas%20get%5D%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A32180)%0A%20%20%20%20at%20Object.decorator%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A30436)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A7%3A74957%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A33212)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A31027)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A31338%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A30821)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.5%2F%24injector%2Fmodulerr%3Fp0%3Dapp%252Fvisualize%26p1%3DError%253A%2520%255B%2524injector%253Aunpr%255D%2520Unknown%2520provider%253A%2520visEditorAggDirectiveProvider%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.6.5%252F%2524injector%252Funpr%253Fp0%253DvisEditorAggDirectiveProvider%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A996%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A34101%250A%2520%2520%2520%2520at%2520Object.getService%2520%255Bas%2520get%255D%2520(http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A32180)%250A%2520%2520%2520%2520at%2520Object.decorator%2520(http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A30436)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A7%253A74957%250A%2520%2520%2520%2520at%2520Object.invoke%2520(http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A33212)%250A%2520%2520%2520%2520at%2520runInvokeQueue%2520(http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A31027)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A31338%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A1681)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A5696%252Fbundles%252Fcommons.bundle.js%253Fv%253D16337%253A48%253A30821)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A996%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A31683%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A30821)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A31240%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A30821)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A34614)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A13733)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2Flocalhost%3A5696%2Fbundles%2Fcommons.bundle.js%3Fv%3D16337%3A48%3A14265) (http://localhost:5696/bundles/commons.bundle.js?v=16337:48)
    at window.onerror (http://localhost:5696/bundles/commons.bundle.js?v=16337:64:8723)`

**Comment by tcharlot-datasweet** [comment]
Duplicate with #2 .
Please tell us if the patch is working with your conf. Thx.
