### ISSUE TITLE
Release for 6.2.3 and 6.2.4

### ISSUE THREAD

**Issue by Xosmond** [datasweet-fr/kibana-datasweet-formula#10]
Could you please make a release for these versions?

I got an error when i try to install on 6.2.3

```
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [datasweet_formula]. Expected [6.2.3]; found [6.2.2]"
```

**Comment by pedrotcm** [comment]
I tried change the version in package.json, the installation was success but when i started the kibana i got the error message: kibana ace.require is not a function.

**Comment by tcharlot-datasweet** [comment]
Hi @Xosmond, @pedrotcm 
I will provide a new release next week.  Meanwhile you can use the `build.sh` to build your own package.
Regards

**Comment by tcharlot-datasweet** [comment]
Hi @Xosmond , @pedrotcm 

I updated the release for kibana v6.2.3, v6.2.4 : https://github.com/datasweet-fr/kibana-datasweet-formula/releases/tag/v1.0.2
Regards

**Comment by georgezoto** [comment]
@tcharlot-datasweet  you saved the day! This is exactly what I was looking for. Thank you for supporting the newest version of Kibana 6.2.4! Merci Beaucoup 🇫🇷
