### ISSUE TITLE
Result Decimals Places Formatter

### ISSUE THREAD

**Issue by pedrotcm** [datasweet-fr/kibana-datasweet-formula#11]
The formatter in percentage, has how to format the number of decimal places?

**Comment by lfroment-datasweet** [comment]
Hi @pedroctm ,
we do not understand your question. Can you please give some details aout what you mean?

Regards

**Comment by pedrotcm** [comment]
It was the number of decimal places after the comma. In my case I managed to solve using the following formula to have two decimal places:
`round(agg1 / agg2 * 10000.0) / 10000.0`

**Comment by vanhul** [comment]
@pedrotcm You are a fucking genious!
