### ISSUE TITLE
kibana_dashboard_only_user error for visualizations created in kibana-datasweet 

### ISSUE THREAD

**Issue by georgezoto** [datasweet-fr/kibana-datasweet-formula#12]
Hello datasweet team,

I was super excited when I came across your plugin yesterday. I created a simple ratio of two aggregations and added them to a dashboard 📈.

However, when viewing this dashboard in dashboard_only_mode, all my regular visualizations were displayed properly except for the one I created with datasweet 📉 .

Below is my role configuration for the user with `kibana_dashboard_only_user` role. I tried elevating him and granted him access to `.kibana` index and `all` privileges but I still get the same **error**: 
`Visualize: undefined is not an object (evaluating 'agg.type.postFlightRequest')`

Note that I do not see this error with the superuser. I tried giving my dashboard only user privileges similar to a superuser but I still get the same error with **no visualization** (the **data** is there though available for export)

Below are some screenshots for this issue. 
Please help us out as this is breaking our dashboard.

Happy to assist in any way I can,
George 

![roles](https://user-images.githubusercontent.com/16548373/40189117-97637852-59c9-11e8-9bd3-b2c82cb53016.jpg)

![dashdoard mode error](https://user-images.githubusercontent.com/16548373/40189162-b8730940-59c9-11e8-8766-c14891d1d833.jpg)

**Comment by tcharlot-datasweet** [comment]
Hi @georgezoto 
Please try the last release (v1.1.0)
