### ISSUE TITLE
Hidden aggregation are visible. How solve problem?

### ISSUE THREAD

**Issue by anomaliyao** [datasweet-fr/kibana-datasweet-formula#16]
Install plugin for Kibana 6.1.2.
Under the superuser, widget with metrics hides some metrics(aggregation) that are needed to calculate the metrics.

And if you go to the kibana under the user with role "kibana_dashboard_only_user", then all the hidden aggregation are visible.

I need help. I will be very grateful!!

**Comment by simpleuser99** [comment]
I have the same problem.

**Comment by lfroment-datasweet** [comment]
Hi, thank you both for your comments. We need to investigate/test this properly, as we do not use Xpacks features or dahsboard_only mode as a standard.

**Comment by simpleuser99** [comment]
@lfroment-datasweet , This is a very serious problem for me.
I really want to quickly solve the problem, I would be approached and a temporary solution, so that I was not forced to abandon the use of the plug-in. I am ready to participate in the solution of the problem, please can you promptly help me?
my contacts: 
https://t.me/pullmix
pullmix@gmail.com
Thak you.

**Comment by lfroment-datasweet** [comment]
Hi @anomaliyao and @simpleuser99 
Trying, to reproduce, it seems I have a different behavior. In dashboard_only mode, I can see the input agg, but I cannnot see the formula output. Can you confirm that you see both? Could you please post some screenshots ?

**Comment by simpleuser99** [comment]
> I can see the input agg, but I cannnot see the formula output
Yes, I have the same bug.
My screenshots:
create vizualization:
![create_viz](https://user-images.githubusercontent.com/11714750/40533467-930da5fa-600b-11e8-99c2-78b111ea7bd0.JPG)
View in default dashbord mode
![superuser_dash](https://user-images.githubusercontent.com/11714750/40533469-9709ffdc-600b-11e8-8d0c-4ed9443146c9.JPG)
View in dashboard_only mode
![readonly_dash](https://user-images.githubusercontent.com/11714750/40533470-98e068d2-600b-11e8-9e19-7815557d569b.JPG)

**Comment by lfroment-datasweet** [comment]
Ok, we are on it.

**Comment by simpleuser99** [comment]
Do you have a fix?

**Comment by lfroment-datasweet** [comment]
Hi we are figuring out how to solve this. It might take some time.

**Comment by anomaliyao** [comment]
Can you tell me when it's possible to solve this?

**Comment by simpleuser99** [comment]
@lfroment-datasweet , Did you solve the problem? Will there be a fix?

**Comment by tcharlot-datasweet** [comment]
Hi @simpleuser99 , @anomaliyao 
Please try the last release. 
Thanks.

**Comment by simpleuser99** [comment]
@lfroment-datasweet , @tcharlot-datasweet  Great Thanks! Fix is work!
