### ISSUE TITLE
Error Kibana After Instalation

### ISSUE THREAD

**Issue by olozada** [datasweet-fr/kibana-datasweet-formula#2]
Good mornig i just Install the plug in and kibana stop working, the I uninstall the plugin an kibana start working fine, i am using version 6.2.1, I dont Know if i am installing the plugin with the wron parameters.

I'm using -d , but it seems is deprecated.

Atte.
Oscar Lozada

**Comment by olozada** [comment]
Uncaught Error: [$injector:modulerr] Failed to instantiate module kibana due to:
Error: [$injector:modulerr] Failed to instantiate module app/visualize due to:
Error: [$injector:unpr] Unknown provider: visEditorAggDirectiveProvider
http://errors.angularjs.org/1.6.5/$injector/unpr?p0=visEditorAggDirectiveProvider
    at http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:996
    at http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:34101
    at Object.getService [as get] (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:32180)
    at Object.decorator (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:30436)
    at http://35.196.94.217:5601/bundles/commons.bundle.js?v=16573:1:299371
    at Object.invoke (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:33212)
    at runInvokeQueue (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:31027)
    at http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:31338
    at forEach (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:1681)
    at loadModules (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:30821)
    at http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:31240
    at forEach (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:1681)
    at loadModules (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:30821)
    at createInjector (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:34614)
    at doBootstrap (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:13733)
    at Object.bootstrap (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:14265)
http://errors.angularjs.org/1.6.5/$injector/modulerr?p0=app%2Fvisualize&p1=Error%3A%20%5B%24injector%3Aunpr%5D%20Unknown%20provider%3A%20visEditorAggDirectiveProvider%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.5%2F%24injector%2Funpr%3Fp0%3DvisEditorAggDirectiveProvider%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A996%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A34101%0A%20%20%20%20at%20Object.getService%20%5Bas%20get%5D%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A32180)%0A%20%20%20%20at%20Object.decorator%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A30436)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fcommons.bundle.js%3Fv%3D16573%3A1%3A299371%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A33212)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A31027)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A31338%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A30821)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A31240%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A30821)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A34614)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A13733)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A14265)
    at http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:996
    at http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:31683
    at forEach (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:1681)
    at loadModules (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:30821)
    at http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:31240
    at forEach (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:1681)
    at loadModules (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:30821)
    at createInjector (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:34614)
    at doBootstrap (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:13733)
    at Object.bootstrap (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123:14265)
    at Object.chrome.bootstrap (http://35.196.94.217:5601/bundles/commons.bundle.js?v=16573:21:429447)
    at Object.4170 (http://35.196.94.217:5601/bundles/logout.bundle.js?v=16573:1:606)
    at __webpack_require__ (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:1:223)
    at window.webpackJsonp (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:1:918)
    at http://35.196.94.217:5601/bundles/logout.bundle.js?v=16573:1:1
http://errors.angularjs.org/1.6.5/$injector/modulerr?p0=kibana&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20app%2Fvisualize%20due%20to%3A%0AError%3A%20%5B%24injector%3Aunpr%5D%20Unknown%20provider%3A%20visEditorAggDirectiveProvider%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.5%2F%24injector%2Funpr%3Fp0%3DvisEditorAggDirectiveProvider%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A996%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A34101%0A%20%20%20%20at%20Object.getService%20%5Bas%20get%5D%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A32180)%0A%20%20%20%20at%20Object.decorator%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A30436)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fcommons.bundle.js%3Fv%3D16573%3A1%3A299371%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A33212)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A31027)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A31338%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A30821)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A31240%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A30821)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A34614)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A13733)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A14265)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.5%2F%24injector%2Fmodulerr%3Fp0%3Dapp%252Fvisualize%26p1%3DError%253A%2520%255B%2524injector%253Aunpr%255D%2520Unknown%2520provider%253A%2520visEditorAggDirectiveProvider%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.6.5%252F%2524injector%252Funpr%253Fp0%253DvisEditorAggDirectiveProvider%250A%2520%2520%2520%2520at%2520http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A996%250A%2520%2520%2520%2520at%2520http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A34101%250A%2520%2520%2520%2520at%2520Object.getService%2520%255Bas%2520get%255D%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A32180)%250A%2520%2520%2520%2520at%2520Object.decorator%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A30436)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fcommons.bundle.js%253Fv%253D16573%253A1%253A299371%250A%2520%2520%2520%2520at%2520Object.invoke%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A33212)%250A%2520%2520%2520%2520at%2520runInvokeQueue%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A31027)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A31338%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A1681)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A30821)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A31240%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A1681)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A30821)%250A%2520%2520%2520%2520at%2520createInjector%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A34614)%250A%2520%2520%2520%2520at%2520doBootstrap%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A13733)%250A%2520%2520%2520%2520at%2520Object.bootstrap%2520(http%253A%252F%252F35.196.94.217%253A5601%252Fbundles%252Fvendors.bundle.js%253Fv%253D16573%253A123%253A14265)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A996%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A31683%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A30821)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A31240%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A1681)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A30821)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A34614)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A13733)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A123%3A14265)%0A%20%20%20%20at%20Object.chrome.bootstrap%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fcommons.bundle.js%3Fv%3D16573%3A21%3A429447)%0A%20%20%20%20at%20Object.4170%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Flogout.bundle.js%3Fv%3D16573%3A1%3A606)%0A%20%20%20%20at%20__webpack_require__%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A1%3A223)%0A%20%20%20%20at%20window.webpackJsonp%20(http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Fvendors.bundle.js%3Fv%3D16573%3A1%3A918)%0A%20%20%20%20at%20http%3A%2F%2F35.196.94.217%3A5601%2Fbundles%2Flogout.bundle.js%3Fv%3D16573%3A1%3A1 (http://35.196.94.217:5601/bundles/vendors.bundle.js?v=16573:123)

**Comment by tcharlot-datasweet** [comment]
Hi it seems there is an issue with xpack / searchguard. We need to investigate. Thx for the report.

**Comment by tcharlot-datasweet** [comment]
Hi. You can try the new release 1.0.1 and tell us if its ok now. Thanks for your review.

**Comment by srolskyi** [comment]
thx! works for me

**Comment by tcharlot-datasweet** [comment]
Hi @olozada ! Is it ok for you ?
