### ISSUE TITLE
Table Footer Formula

### ISSUE THREAD

**Issue by gmatheus** [datasweet-fr/kibana-datasweet-formula#4]
Hey,

I've noticed is that the formula doesn't work as expected for the "Total" table function. For example, I'm using `sum` function in the image below:
![screen shot 2018-03-05 at 18 20 22](https://user-images.githubusercontent.com/16384428/37002375-4370694e-20a8-11e8-95fd-7d828c75ae2c.png)

Shouldn't the last column (a derived metric as percentage) be calculated by the formula as well? I mean, first sum the column values and then apply the formula (`sum(agg1)/sum(agg3)`)?

Thanks!

**Comment by tcharlot-datasweet** [comment]
Hi ! 
At the moment, the _total_ function is defined by kibana. I will see if i can override it. 
Thx for your report =)

**Comment by gmatheus** [comment]
@tcharlot-datasweet Hey, I fixed this bug in #14!
Feel free to comment and suggest changes 🙂
