### ISSUE TITLE
kibana-datasweet-formula for kibana 6.2.2

### ISSUE THREAD

**Issue by DiegovelascoF** [datasweet-fr/kibana-datasweet-formula#6]
When I try to install the plugin for kibana 6.2.2, a message with incorrect plugin version appears. Is there a way to install it in 6.2.2? If not, when will we have a release for this version of kibana?

**Comment by lfroment-datasweet** [comment]
Hi, on it for 6.2.2 version. Some correction has to be done before.
stay tuned.
Regards

**Comment by tcharlot-datasweet** [comment]
Hi, please try the new release v1.0.2 !

**Comment by DiegovelascoF** [comment]
Thanks!!
Great job
