### ISSUE TITLE
Datasweet Formula invisible in metric visualization

### ISSUE THREAD

**Issue by v01t** [datasweet-fr/kibana-datasweet-formula#7]
Hello,

Kibana version: 6.2.0
Problem: Datasweet Formula result value invisible in metric visualization, but correctly calculated and can be seen in a result table:
![screenshot_20180312_112004](https://user-images.githubusercontent.com/3255436/37278351-beb4f1f8-25e7-11e8-94bd-b5ab78ada612.png)

**Comment by lfroment-datasweet** [comment]
Thanks for your report. We will investigate and correct that soon.

**Comment by v01t** [comment]
was fixed with v.1.0.2

Thanks
