### ISSUE TITLE
Datasweet Formula doesn't work with percentiles aggregation

### ISSUE THREAD

**Issue by v01t** [datasweet-fr/kibana-datasweet-formula#8]
Hello,

Kibana version: 6.2.0
Problem: Datasweet Formula calculation doesn't work with percentiles aggregation (even when only one percentile selected)

It may be hard to implement or require a lot of changes in case of multiple percentiles selected for same field/metric (like: 25,50,75) but it should be possible to fix when single percentile selected.

Thanks for such a great plugin.

**Comment by tcharlot-datasweet** [comment]
Same issue than #5 
We are working on it.

**Comment by tcharlot-datasweet** [comment]
Hi, please try the new release v1.0.2 !

**Comment by v01t** [comment]
HI @tcharlot-datasweet,

thanks for update, I just test latest 1.0.2 version, derivation aggregation (#5) works now, same for percentiles, with the following syntax in formula:
- `aggX_PERCENTILEVALUE`

maybe it will be a good improvement (to cover all possible similar cases and functionality) in future to retrieve them in a formula like:
`aggX[99]`
for 99 percentile, see more detailed comment in #5 

Thanks a lot for your work.
